#include "GcodeInfoScanner.hpp"

#include <algorithm>
#include <charconv>
#include <cstdio>
#include <cstring>
#include <functional>
#include <utility>

#include <boost/beast/core/detail/base64.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/format.hpp>
#include <boost/log/trivial.hpp>
#include <boost/nowide/cstdio.hpp>



namespace Slic3r {

namespace {

// Producer signatures, in match order. "generated by AnkerMake Studio" has to be
// tested before the bare "AnkerMake" or every AnkerStudio file reads as AnkerMake.
const std::vector<std::pair<GcodeInfoScanner::EProducer, std::string>> Producers = {
    { GcodeInfoScanner::EProducer::AnkerStudio, "generated by AnkerMake Studio" },
    { GcodeInfoScanner::EProducer::PrusaSlicer, "generated by PrusaSlicer" },
    { GcodeInfoScanner::EProducer::Slic3rPE,    "generated by Slic3r Anker Edition" },
    { GcodeInfoScanner::EProducer::Slic3r,      "generated by Slic3r" },
    { GcodeInfoScanner::EProducer::SuperSlicer, "generated by SuperSlicer" },
    { GcodeInfoScanner::EProducer::Cura,        "Cura_SteamEngine" },
    { GcodeInfoScanner::EProducer::Simplify3D,  "generated by Simplify3D(R)" },
    { GcodeInfoScanner::EProducer::CraftWare,   "CraftWare" },
    { GcodeInfoScanner::EProducer::ideaMaker,   "ideaMaker" },
    { GcodeInfoScanner::EProducer::KissSlicer,  "KISSlicer" },
    { GcodeInfoScanner::EProducer::BambuStudio, "BambuStudio" },
    { GcodeInfoScanner::EProducer::AnkerMake,   "AnkerMake" },
};

inline const char* skip_whitespaces(const char* begin, const char* end)
{
    for (; begin != end && (*begin == ' ' || *begin == '\t'); ++begin);
    return begin;
}

inline const char* remove_eols(const char* begin, const char* end)
{
    for (; begin != end && (*(end - 1) == '\r' || *(end - 1) == '\n'); --end);
    return end;
}

struct FileHandle
{
    FILE* f = nullptr;
    explicit FileHandle(const std::string& path) : f(boost::nowide::fopen(path.c_str(), "rb")) {}
    ~FileHandle() { if (f) ::fclose(f); }
    FileHandle(const FileHandle&) = delete;
    FileHandle& operator=(const FileHandle&) = delete;
};

// Reads the file in chunks and hands each raw line to `callback`. The callback
// sets `stop` to abandon the rest of the file. Lifted from
// GCodeReader::parse_file_raw_internal(), minus the line-end bookkeeping that
// only the move-parsing path needed.
bool parse_file_raw(const std::string&                                                    path,
                    const std::function<void(const char* begin, const char* end, bool& stop)>& callback)
{
    FileHandle in(path);
    if (!in.f) {
        BOOST_LOG_TRIVIAL(error) << "GcodeInfoScanner: cannot open " << path;
        return false;
    }

    std::vector<char> buffer(65536 * 10, 0);
    std::string       gcode_line;
    bool              stop = false;

    for (;;) {
        const size_t cnt_read = ::fread(buffer.data(), 1, buffer.size(), in.f);
        if (::ferror(in.f))
            return false;
        const bool eof       = cnt_read == 0;
        auto       it        = buffer.begin();
        auto       it_bufend = buffer.begin() + cnt_read;

        while (it != it_bufend || (eof && !gcode_line.empty())) {
            bool eol    = false;
            auto it_end = it;
            for (; it_end != it_bufend && !(eol = *it_end == '\r' || *it_end == '\n'); ++it_end);
            eol |= eof && it_end == it_bufend;

            if (eol) {
                if (gcode_line.empty())
                    callback(&(*it), &(*it_end), stop);
                else {
                    gcode_line.insert(gcode_line.end(), it, it_end);
                    callback(gcode_line.c_str(), gcode_line.c_str() + gcode_line.size(), stop);
                    gcode_line.clear();
                }
                if (stop)
                    return true;
            } else
                gcode_line.insert(gcode_line.end(), it, it_end);

            it = it_end;
            if (it != it_bufend && *it == '\r')
                ++it;
            if (it != it_bufend && *it == '\n')
                ++it;
        }
        if (eof)
            break;
    }
    return true;
}

// The original parses these with std::stof / sscanf straight off the comment.
// Malformed input would throw out through the read loop, so the numeric helpers
// here fail the match instead.
bool to_float(std::string_view text, float& value)
{
    try {
        value = std::stof(std::string(text));
        return true;
    } catch (...) {
        return false;
    }
}

int time_to_seconds(const std::string& time)
{
    int days = 0, hours = 0, minutes = 0, seconds = 0;
    if (time.find('d') != std::string::npos)
        ::sscanf(time.c_str(), "%dd %dh %dm %ds", &days, &hours, &minutes, &seconds);
    else if (time.find('h') != std::string::npos)
        ::sscanf(time.c_str(), "%dh %dm %ds", &hours, &minutes, &seconds);
    else if (time.find('m') != std::string::npos)
        ::sscanf(time.c_str(), "%dm %ds", &minutes, &seconds);
    else if (time.find('s') != std::string::npos)
        ::sscanf(time.c_str(), "%ds", &seconds);

    return days * 24 * 60 * 60 + hours * 60 * 60 + minutes * 60 + seconds;
}

} // namespace

void GcodePrintInfo::reset()
{
    base64_str.clear();
    speed.clear();
    filament_used_weight_g.clear();
    filament_used_length_mm.clear();
    filament_used_cost.clear();
    print_time = 0.0f;
    boxSize.fill(0.0f);
}

bool GcodeInfoScanner::DetectProducer(std::string_view comment, EProducer& producer)
{
    for (const auto& [id, search_string] : Producers) {
        if (comment.find(search_string) != std::string_view::npos) {
            producer = id;
            BOOST_LOG_TRIVIAL(info) << "Detected gcode producer: " << search_string;
            return true;
        }
    }
    return false;
}

bool GcodeInfoScanner::SearchThumbnailBegin(std::string_view line, EProducer producer,
                                            const std::string& format, int task_flag)
{
    // Thumbnail already captured.
    if (task_flag & (1 << 0))
        return false;

    std::string search_string = "thumbnail begin 256 256";
    if (producer == EProducer::AnkerStudio || producer == EProducer::PrusaSlicer)
        search_string = "thumbnail begin 256x256";
    if (!format.empty())
        // AnkerMake always keeps "thumbnail begin 256 256".
        search_string = (boost::format("thumbnail_%s begin %dx%d") % format % 256 % 256).str();

    if (line.find(search_string) != std::string_view::npos) {
        BOOST_LOG_TRIVIAL(info) << "search gcode thumbnail: " << search_string;
        return true;
    }
    return false;
}

bool GcodeInfoScanner::SearchThumbnailEnd(std::string_view line, const std::string& format,
                                          bool has_searched_tag)
{
    if (!has_searched_tag)
        return false;

    std::string search_string = format.empty() ? std::string("thumbnail end")
                                               : (boost::format("thumbnail_%s end") % format).str();
    if (line.find(search_string) != std::string_view::npos) {
        BOOST_LOG_TRIVIAL(info) << "Detected gcode thumbnail end: " << search_string;
        return true;
    }
    return false;
}

bool GcodeInfoScanner::SearchSpeed(std::string_view line, EProducer producer, std::string& speed)
{
    if (producer == EProducer::AnkerMake) {
        const std::string search_string = "MAXSPEED:";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            const std::string_view value = line.substr(pos + search_string.length());
            int                    max_speed = 0;
            const auto             result = std::from_chars(value.data(), value.data() + value.size(), max_speed);
            if (result.ec != std::errc())
                return false;
            speed = std::to_string(max_speed / 60);
            return true;
        }
        return false;
    }

    if (producer == EProducer::AnkerStudio) {
        const std::string search_string = "max_print_speed =";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            speed = line.substr(pos + search_string.length());
            return true;
        }
        return false;
    }

    return false;
}

bool GcodeInfoScanner::SearchObjSize(std::string_view line, EProducer producer,
                                     std::array<float, 3>& boxSize)
{
    if (producer != EProducer::AnkerMake && producer != EProducer::AnkerStudio)
        return false;

    const size_t colon_pos = line.find(':');
    if (colon_pos == std::string_view::npos)
        return false;

    const std::string_view key   = line.substr(0, colon_pos);
    const std::string_view value = line.substr(colon_pos + 1);

    float v = 0.f;
    if (key == "MINX") { if (to_float(value, v)) boxSize[0] -= v; }
    else if (key == "MINY") { if (to_float(value, v)) boxSize[1] -= v; }
    else if (key == "MINZ") { if (to_float(value, v)) boxSize[2] -= v; }
    else if (key == "MAXX") { if (to_float(value, v)) boxSize[0] += v; }
    else if (key == "MAXY") { if (to_float(value, v)) boxSize[1] += v; }
    else if (key == "MAXZ") {
        if (to_float(value, v)) {
            boxSize[2] += v;
            // MAXZ is emitted last, so the box is complete here.
            return true;
        }
    }
    return false;
}

bool GcodeInfoScanner::SearchFilamentWeight(std::string_view line, EProducer producer, std::string& weight)
{
    if (producer == EProducer::AnkerMake) {
        const std::string search_string = "Filament weight:";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            weight = line.substr(pos + search_string.length());
            return true;
        }
        return false;
    }

    if (producer == EProducer::AnkerStudio) {
        const std::string search_string = "total filament used [g] =";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            weight = line.substr(pos + search_string.length());
            weight += "g";
            return true;
        }
        return false;
    }
    return false;
}

bool GcodeInfoScanner::SearchFilamentLength(std::string_view line, EProducer producer, std::string& length)
{
    if (producer == EProducer::AnkerMake) {
        const std::string search_string = "Filament used:";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            length = line.substr(pos + search_string.length());
            return true;
        }
        return false;
    }

    if (producer == EProducer::AnkerStudio) {
        const std::string search_string = "filament used [mm] =";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            length = line.substr(pos + search_string.length());
            length += "mm";
            return true;
        }
        return false;
    }
    return false;
}

bool GcodeInfoScanner::SearchFilamentCost(std::string_view line, EProducer producer, std::string& cost)
{
    if (producer != EProducer::AnkerStudio)
        return false;

    const std::string search_string = "total filament cost =";
    const size_t      pos           = line.find(search_string);
    if (pos != std::string_view::npos) {
        cost = line.substr(pos + search_string.length());
        return true;
    }
    return false;
}

bool GcodeInfoScanner::SearchPrintTime(std::string_view line, EProducer producer, float& print_time)
{
    if (producer == EProducer::AnkerMake || producer == EProducer::AnkerStudio) {
        const std::string search_string = "TIME:";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            print_time = static_cast<float>(time_to_seconds(std::string(line.substr(pos + search_string.length()))));
            return true;
        }
    }

    if (producer == EProducer::PrusaSlicer || producer == EProducer::AnkerStudio) {
        const std::string search_string = "estimated printing time (normal mode) = ";
        const size_t      pos           = line.find(search_string);
        if (pos != std::string_view::npos) {
            print_time = static_cast<float>(time_to_seconds(std::string(line.substr(pos + search_string.length()))));
            return true;
        }
        return false;
    }
    return false;
}

bool GcodeInfoScanner::Scan(const std::string& utf8Path, GcodePrintInfo& out)
{
    out.reset();

    EProducer producer            = EProducer::Unknown;
    bool      has_detect_producer = false;
    bool      has_searched_thumbtag = false;
    std::string format;

    // Bit per field: 0 thumbnail, 1 speed, 2 filament weight, 3 filament length,
    // 4 filament cost, 5 print time, 6 object size. All seven set -> stop reading.
    int task_flag = 0;

    {
        boost::filesystem::path p(utf8Path);
        std::string             ext = p.extension().string();
        std::transform(ext.begin(), ext.end(), ext.begin(), ::tolower);
        if (ext == ".acode") {
            // .acode carries no producer comment; it is always AnkerMake.
            has_detect_producer = true;
            producer            = EProducer::AnkerMake;
        }
    }

    return parse_file_raw(utf8Path, [&](const char* begin, const char* end, bool& stop) {
        begin = skip_whitespaces(begin, end);
        if (begin == end || *begin != ';')
            return;

        // Comment body, without the ';' or the trailing newline.
        begin = skip_whitespaces(++begin, end);
        end   = remove_eols(begin, end);
        if (begin == end)
            return;

        const std::string_view comment(begin, end - begin);

        if (!has_detect_producer) {
            if (DetectProducer(comment, producer))
                has_detect_producer = true;
            return;
        }

        if (producer != EProducer::AnkerMake && producer != EProducer::AnkerStudio &&
            producer != EProducer::PrusaSlicer && producer != EProducer::Cura) {
            // Recognised producer we have no comment grammar for.
            stop = true;
            return;
        }

        // 0b111'1111 -- every field found.
        if (task_flag >= 127) {
            stop = true;
            return;
        }

        if (SearchThumbnailEnd(comment, format, has_searched_thumbtag)) {
            task_flag |= (1 << 0);
            has_searched_thumbtag = false;
            return;
        }

        // Between the begin and end markers every comment line is payload.
        if (has_searched_thumbtag) {
            out.base64_str.append(begin, end);
            return;
        }

        if (SearchThumbnailBegin(comment, producer, format, task_flag)) {
            has_searched_thumbtag = true;
            return;
        }
        if (SearchSpeed(comment, producer, out.speed)) {
            task_flag |= (1 << 1);
            return;
        }
        if (SearchFilamentWeight(comment, producer, out.filament_used_weight_g)) {
            task_flag |= (1 << 2);
            return;
        }
        if (SearchFilamentLength(comment, producer, out.filament_used_length_mm)) {
            task_flag |= (1 << 3);
            return;
        }
        if (SearchFilamentCost(comment, producer, out.filament_used_cost)) {
            task_flag |= (1 << 4);
            return;
        }
        if (SearchPrintTime(comment, producer, out.print_time)) {
            task_flag |= (1 << 5);
            return;
        }
        if (SearchObjSize(comment, producer, out.boxSize)) {
            task_flag |= (1 << 6);
            return;
        }
    });
}

std::vector<unsigned char> GcodeInfoScanner::DecodeBase64(const std::string& base64)
{
    std::vector<unsigned char> binary;
    if (base64.empty())
        return binary;

    binary.resize(boost::beast::detail::base64::decoded_size(base64.length()));
    const auto decoded = boost::beast::detail::base64::decode(binary.data(), base64.c_str(), base64.length());
    binary.resize(decoded.first);
    return binary;
}

} // namespace Slic3r
